### ISSUE TITLE
why it is better than other similar packages 

### ISSUE THREAD

**Issue by Sandy4321** [Techtonique/teller#3]
do you have example 
why it is better than other similar packages

**Comment by thierrymoudiki** [comment]
Hi @Sandy4321 ,

This is not an issue... Have you tested the code?

Well, there are different ways to tackle the question of explainability, **that can coexist**! Don't you think so?

**Comment by thierrymoudiki** [comment]
@Sandy4321 Shall we close the issue?

**Comment by Sandy4321** [comment]
yes it is the question 
what your code doing better than other packages
for sure you doing something better ...

**Comment by thierrymoudiki** [comment]
@Sandy4321 maybe it's just easier and intuitive to work with derivatives. Not better, it's different.

**Comment by thierrymoudiki** [comment]
@Sandy4321 : shall we close this issue?
